### ISSUE TITLE
LocalHost:8000 Gets Crash  

### ISSUE THREAD

**Issue by saishinkar2** [dhdhagai/SciPoTech#2]
<img width="1792" alt="Screenshot 2023-08-15 at 12 25 21 PM" src="https://github.com/dhdhagai/SciPoTech/assets/116909682/6a742bf7-dd39-48ca-a468-b21506ae6443">

localhost:8000 is not working properly

**Comment by dhdhagai** [comment]
``node index`` must be run in  the folder where the repository has been cloned
@saishinkar2
