### ISSUE TITLE
OpenAI Credits Issue

### ISSUE THREAD

**Issue by saishinkar2** [dhdhagai/SciPoTech#4]
<img width="1311" alt="Screenshot 2023-08-15 at 11 26 25 PM" src="https://github.com/dhdhagai/SciPoTech/assets/116909682/97b9c8ec-5e0b-4e63-b6b7-57672e16654a">

Getting OpenAi Api trial version credits are all used up before using it.

**Comment by dhdhagai** [comment]
It seems that OpenAi Doesn't allow their services for free and will require only the paid users to work with it. Will note down the issue and work with it asap. Please find other Ai Services that give their API for completely free.
