### ISSUE TITLE
Git Issue On Linux & MacOS

### ISSUE THREAD

**Issue by dhdhagai** [dhdhagai/SciPoTech#5]
# Version
Ventura
# Issue
Git Version not being installed, it wont work with the default login feature which was a text-based ui, now changed to the browser authencation method for security reasons, doesn't open everytime on Linux and MacOS. 
Faced The Issues a few minutes ago.

**Comment by saishinkar2** [comment]
It seems to be like MacOS & Linux Terminals have some problems with authentication process for GitHub Login., Either check your login credentials or as mentioned do it via VS Code which uses browser authentication process.

**Comment by dhdhagai** [comment]
This issue is necessary and must be opened until we find a perfect workaround. Please see to it that we complete this ASAP.

**Comment by saishinkar2** [comment]
Okay ., Let's Find the Solution To this Issue

**Comment by dhdhagai** [comment]
Closing Issue, Seems like this issue is no longer required as the error is not appearing on my kali linux machine.

**Comment by saishinkar2** [comment]
Let me Solve For macOS

**Comment by saishinkar2** [comment]
After using visual studio code's built in git commands, we can login through the browser instead of the prompt that we usually get in the text based login. Closed Reason - Completed. Reopened Reason- MacOS Issue still permits.
